// main products dataBase \\
let products = [
  {
    id: 1,
    title: "Gaming Glass Case ",
    price: 3000,
    src: "Imgs/products/case.png",
    slides: [
      "Imgs/products/case.png",
      "Imgs/products/case.png",
      "Imgs/products/case.png",
    ],
    count: 1,
  },
  {
    id: 2,
    title: "HDMI Cable ",
    price: 30,
    src: "Imgs/products/cable.png",
    slides: [
      "Imgs/products/cable.png",
      "Imgs/products/cable.png",
      "Imgs/products/cable.png",
    ],
    count: 1,
  },
  {
    id: 3,
    title: "Camera",
    price: 500,
    src: "Imgs/products/camera.png",
    slides: [
      "Imgs/products/camera.png",
      "Imgs/products/camera.png",
      "Imgs/products/camera.png",
    ],
    count: 1,
  },
  {
    id: 4,
    title: "Graphic Card",
    price: 2000,
    src: "Imgs/products/card.png",
    slides: [
      "Imgs/products/card.png",
      "Imgs/products/card.png",
      "Imgs/products/card.png",
    ],
    count: 1,
  },
  {
    id: 5,
    title: "Controller",
    price: 500,
    src: "Imgs/products/control.png",
    slides: [
      "Imgs/products/control.png",
      "Imgs/products/control.png",
      "Imgs/products/control.png",
    ],
    count: 1,
  },
  {
    id: 6,
    title: "I5 Cpu",
    price: 1200,
    src: "Imgs/products/cpu.png",
    slides: [
      "Imgs/products/cpu.png",
      "Imgs/products/cpu.png",
      "Imgs/products/cpu.png",
    ],
    count: 1,
  },
  {
    id: 7,
    title: "Cpu Fan",
    price: 200,
    src: "Imgs/products/CPUFAN.png",
    slides: [
      "Imgs/products/CPUFAN.png",
      "Imgs/products/CPUFAN.png",
      "Imgs/products/CPUFAN.png",
    ],
    count: 1,
  },
  {
    id: 8,
    title: "HeadPhone",
    price: 450,
    src: "Imgs/products/game-headphone.png",
    slides: [
      "Imgs/products/game-headphone.png",
      "Imgs/products/game-headphone.png",
      "Imgs/products/game-headphone.png",
    ],
    count: 1,
  },
  {
    id: 9,
    title: "Gaming Keyboard",
    price: 340,
    src: "Imgs/products/keyboard.png",
    slides: [
      "Imgs/products/keyboard.png",
      "Imgs/products/keyboard.png",
      "Imgs/products/keyboard.png",
    ],
    count: 1,
  },
  {
    id: 10,
    title: "Gaming Mouse",
    price: 150,
    src: "Imgs/products/mouse.png",
    slides: [
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
    ],
    count: 1,
  },
  {
    id: 11,
    title: "Gaming Table",
    price: 1000,
    src: "Imgs/products/table.png",
    slides: [
      "Imgs/products/table.png",
      "Imgs/products/table.png",
      "Imgs/products/table.png",
    ],
    count: 1,
  },
  {
    id: 12,
    title: " SAM TV",
    price: 1300,
    src: "Imgs/products/tv.png",
    slides: [
      "Imgs/products/tv.png",
      "Imgs/products/tv.png",
      "Imgs/products/tv.png",
    ],
    count: 1,
  },
  {
    id: 13,
    title: "USB",
    price: 30,
    src: "Imgs/products/usb.png",
    slides: [
      "Imgs/products/usb.png",
      "Imgs/products/usb.png",
      "Imgs/products/usb.png",
    ],
    count: 1,
  },
  {
    id: 14,
    title: "Gaming Mouse",
    price: 150,
    src: "Imgs/products/mouse.png",
    slides: [
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
    ],
    count: 1,
  },
];
// main products dataBase \\