// main products dataBase \\
let products = [
  {
    id: 1,
    title: "Gaming Glass Case ",
    price: 3000,
    src: "Imgs/products/case.png",
    slides: [
      "Imgs/products/case.png",
      "Imgs/products/case.png",
      "Imgs/products/case.png",
    ],
    count: 1,
  },
  {
    id: 2,
    title: "HDMI Cable ",
    price: 30,
    src: "Imgs/products/cable.png",
    slides: [
      "Imgs/products/cable.png",
      "Imgs/products/cable.png",
      "Imgs/products/cable.png",
    ],
    count: 1,
  },
  {
    id: 3,
    title: "Camera",
    price: 500,
    src: "Imgs/products/camera.png",
    slides: [
      "Imgs/products/camera.png",
      "Imgs/products/camera.png",
      "Imgs/products/camera.png",
    ],
    count: 1,
  },
  {
    id: 4,
    title: "Graphic Card",
    price: 2000,
    src: "Imgs/products/card.png",
    slides: [
      "Imgs/products/card.png",
      "Imgs/products/card.png",
      "Imgs/products/card.png",
    ],
    count: 1,
  },
  {
    id: 5,
    title: "Controller",
    price: 500,
    src: "Imgs/products/control.png",
    slides: [
      "Imgs/products/control.png",
      "Imgs/products/control.png",
      "Imgs/products/control.png",
    ],
    count: 1,
  },
  {
    id: 6,
    title: "I5 Cpu",
    price: 1200,
    src: "Imgs/products/cpu.png",
    slides: [
      "Imgs/products/cpu.png",
      "Imgs/products/cpu.png",
      "Imgs/products/cpu.png",
    ],
    count: 1,
  },
  {
    id: 7,
    title: "Cpu Fan",
    price: 200,
    src: "Imgs/products/CPUFAN.png",
    slides: [
      "Imgs/products/CPUFAN.png",
      "Imgs/products/CPUFAN.png",
      "Imgs/products/CPUFAN.png",
    ],
    count: 1,
  },
  {
    id: 8,
    title: "HeadPhone",
    price: 450,
    src: "Imgs/products/game-headphone.png",
    slides: [
      "Imgs/products/game-headphone.png",
      "Imgs/products/game-headphone.png",
      "Imgs/products/game-headphone.png",
    ],
    count: 1,
  },
  {
    id: 9,
    title: "Gaming Keyboard",
    price: 340,
    src: "Imgs/products/keyboard.png",
    slides: [
      "Imgs/products/keyboard.png",
      "Imgs/products/keyboard.png",
      "Imgs/products/keyboard.png",
    ],
    count: 1,
  },
  {
    id: 10,
    title: "Gaming Mouse",
    price: 150,
    src: "Imgs/products/mouse.png",
    slides: [
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
    ],
    count: 1,
  },
  {
    id: 11,
    title: "Gaming Table",
    price: 1000,
    src: "Imgs/products/table.png",
    slides: [
      "Imgs/products/table.png",
      "Imgs/products/table.png",
      "Imgs/products/table.png",
    ],
    count: 1,
  },
  {
    id: 12,
    title: " SAM TV",
    price: 1300,
    src: "Imgs/products/tv.png",
    slides: [
      "Imgs/products/tv.png",
      "Imgs/products/tv.png",
      "Imgs/products/tv.png",
    ],
    count: 1,
  },
  {
    id: 13,
    title: "USB",
    price: 30,
    src: "Imgs/products/usb.png",
    slides: [
      "Imgs/products/usb.png",
      "Imgs/products/usb.png",
      "Imgs/products/usb.png",
    ],
    count: 1,
  },
  {
    id: 14,
    title: "Gaming Mouse",
    price: 150,
    src: "Imgs/products/mouse.png",
    slides: [
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
      "Imgs/products/mouse.png",
    ],
    count: 1,
  },
];
// main products dataBase \\

// sliderImgs \\
let sliderImgs = [
  {
    id: 0,
    src: "Imgs/products/game-headphone.png",
    name: "Headphones & AirPods",
    icon: "WP-213131-ME",
    activeClass: "",
    icon: "Imgs/Icons/icons8-headphones-40.png",
  },
  {
    id: 1,
    src: "imgs/download.png",
    name: "Computer & Laptops",
    icon: "WP-213131",
    activeClass: "",
    icon: "Imgs/Icons/icons8-monitor-40.png",
  },

  {
    id: 2,
    src: "Imgs/products/camera.png",
    name: "Cameras & Lenses",
    icon: "WP-213131-ME",
    activeClass: "",
    icon: "Imgs/Icons/icons8-camera-40.png",
  },
  {
    id: 3,
    src: "Imgs/products/keyboard.png",
    name: "Mouse & Keyboards",
    icon: "WP-213131-ME",
    activeClass: "",
    icon: "Imgs/Icons/icons8-keyboard-40.png",
  },
  {
    id: 4,
    src: "Imgs/products/cable.png",
    name: "Network Cable",
    icon: "WP-213131-ME",
    activeClass: "",
    icon: "Imgs/Icons/cable.png",
  },
  {
    id: 5,
    src: "Imgs/products/tv.png",
    name: "TV & Audio Speakers",
    icon: "WP-213131-ME",
    activeClass: "",
    icon: "Imgs/Icons/icons8-tv-show-40.png",
  },
];
// sliderImgs \\

// specificationItems \\
let specificationItems = [
  { name: "Weight", desc: "7.25kg" },
  { name: "Dimensions", desc: "90 x 60 x 90 cm" },
  { name: "Size", desc: "One Size Fits All" },
  { name: "Color", desc: "Black with Red, White with Gold" },
  { name: "Guarantee", desc: "5 years" },
  { name: "Brand", desc: "Metti" },
  { name: "Item Height", desc: "18 Millimeters" },
  { name: "Item Width", desc: "one size fits all" },
  { name: "Screen Size", desc: "13 Inches" },
  { name: "Item Weight", desc: "1.6kg" },
  { name: "Product Dimensions", desc: "21.9 x 31.4 x 1.8 cm" },
  { name: "Item Model Number", desc: "MF841HN/A" },
  { name: "Processor Brand", desc: "Intel" },
  { name: "Processor Type", desc: "Core I7" },
  { name: "Processor Speed", desc: "3.4 Ghz" },
  { name: "RAM Size", desc: "8 GB" },
  { name: "Hard Drive Size", desc: "512 GB" },
  { name: "Hard Disk Technology", desc: "Solid State Drive" },
  { name: "Graphics Coprocessor", desc: "Intel Integrated Graphics" },
  { name: "Graphic Card Description", desc: "Integrated Graphics Card" },
  { name: "Hardware Platform", desc: "Windows" },
];
// specificationItems \\